# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "tech-leads"
    assignees:
      - "byronwade"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "security-update"
    milestone: 1
    rebase-strategy: "auto"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
    groups:
      # Group React ecosystem updates
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
        exclude-patterns:
          - "react-router*"
      
      # Group Next.js ecosystem updates  
      nextjs-ecosystem:
        patterns:
          - "next*"
          - "@next/*"
      
      # Group testing framework updates
      testing-frameworks:
        patterns:
          - "*jest*"
          - "*vitest*"
          - "*playwright*"
          - "*cypress*"
          - "@testing-library/*"
      
      # Group ESLint and Prettier updates
      code-quality:
        patterns:
          - "*eslint*"
          - "*prettier*"
          - "@typescript-eslint/*"
      
      # Group security-related updates
      security-tools:
        patterns:
          - "*security*"
          - "*audit*"
          - "*snyk*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "tech-leads"
    assignees:
      - "byronwade"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci/cd"
    rebase-strategy: "auto"

  # Enable version updates for Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "tech-leads"
    commit-message:
      prefix: "docker"
    labels:
      - "docker"
      - "infrastructure"