# Streamlined pre-commit hooks for monorepo
# See https://pre-commit.com for more information

default_language_version:
  javascript: system
  typescript: system
fail_fast: true

repos:
  # Essential file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
        exclude: '\.md$'
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: detect-private-key

  # Use local tools for consistency with monorepo
  - repo: local
    hooks:
      # ESLint (using project's version)
      - id: eslint
        name: "ESLint (JavaScript/TypeScript)"
        stages: [pre-commit]
        language: system
        entry: bash -c "npx eslint --fix"
        types: [javascript, typescript, jsx, tsx]
        
      # Prettier (using project's version)
      - id: prettier
        name: "Prettier (Code Formatter)"
        stages: [pre-commit]
        language: system
        entry: bash -c "npx prettier --write"
        types: [javascript, typescript, jsx, tsx, json, yaml, markdown]
        
      # TypeScript type checking
      - id: typescript-check
        name: "TypeScript Type Check"
        stages: [pre-commit]
        language: system
        entry: bash -c "cd apps/main && npx tsc --noEmit"
        files: \.(ts|tsx)$
        pass_filenames: false

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: \.secrets\.baseline$|bun\.lock$

  # Git commit message validation
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

# Global configuration
default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_stages: [commit]

# Performance optimization
minimum_pre_commit_version: '3.0.0'