name: 🔒 Security Vulnerability Report
description: Report a security vulnerability in a responsible manner
title: "[SECURITY] "
labels: ["security", "vulnerability", "urgent"]
assignees:
  - byronwade

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report
        
        **Please do not report security vulnerabilities through public GitHub issues.**
        
        If you believe you have found a security vulnerability, please report it to us through coordinated disclosure.
        
        **Please do not report security vulnerabilities through public GitHub issues, discussions, or pull requests.**
        
        Instead, please send an email to security@thorbis.com with the following information:
        
        - Type of issue (e.g. buffer overflow, SQL injection, cross-site scripting, etc.)
        - Full paths of source file(s) related to the manifestation of the issue
        - The location of the affected source code (tag/branch/commit or direct URL)
        - Any special configuration required to reproduce the issue
        - Step-by-step instructions to reproduce the issue
        - Proof-of-concept or exploit code (if possible)
        - Impact of the issue, including how an attacker might exploit the issue
        
        This information will help us triage your report more quickly.

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Security Reporting Acknowledgment
      description: Please confirm you understand our security reporting process
      options:
        - label: I understand that security vulnerabilities should be reported privately to security@thorbis.com
          required: true
        - label: I have read the project's security policy
          required: true
        - label: This is not a security vulnerability (use regular bug report instead)
          required: false

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of vulnerability is this?
      options:
        - Authentication bypass
        - Authorization bypass  
        - SQL injection
        - Cross-site scripting (XSS)
        - Cross-site request forgery (CSRF)
        - Server-side request forgery (SSRF)
        - Path traversal
        - Code injection
        - Information disclosure
        - Denial of service
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Assessment
      description: How would you rate the severity of this vulnerability?
      options:
        - Critical (Remote code execution, data breach)
        - High (Significant security impact)
        - Medium (Moderate security impact)
        - Low (Minor security impact)
        - Informational (No immediate security risk)
    validations:
      required: true

  - type: textarea
    id: vulnerability-details
    attributes:
      label: Vulnerability Details
      description: |
        Provide a detailed description of the vulnerability.
        **Note: This information will be visible publicly. Do not include sensitive details.**
      placeholder: |
        General description of the vulnerability type and potential impact.
        Do not include specific exploitation details here.
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: Affected Components
      description: Which parts of the application are affected?
      placeholder: |
        - Component name
        - File paths (if known)
        - Affected functionality
    validations:
      required: true

  - type: checkboxes
    id: testing-environment
    attributes:
      label: Testing Environment
      description: Where did you discover this vulnerability?
      options:
        - label: Production environment
        - label: Staging environment
        - label: Local development environment
        - label: Code review

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information that might be helpful
      placeholder: |
        - Browser/environment details
        - Screenshots (if applicable and safe to share)
        - Any additional context

  - type: markdown
    attributes:
      value: |
        ## Next Steps
        
        After submitting this report:
        
        1. **Do not disclose** this vulnerability publicly until we have had a chance to address it
        2. We will acknowledge receipt within 24 hours
        3. We will provide regular updates on our progress
        4. We will notify you when the vulnerability has been fixed
        5. We will coordinate on disclosure timeline if appropriate
        
        Thank you for helping keep our users safe! 🛡️