import React from "react";
import SearchContainer from "@/components/site/search/SearchContainer";
import "mapbox-gl/dist/mapbox-gl.css";
import Script from "next/script";

export const metadata = {
	metadataBase: new URL("https://www.thorbis.com/"),
	title: {
		default: "Thorbis - Discover and Connect with Local Businesses",
		template: "%s | Thorbis",
	},
	description: "Thorbis provides a powerful platform to discover and connect with top-rated local businesses. Explore and find businesses in your area with ease.",
	generator: "Next.js",
	applicationName: "Thorbis",
	keywords: ["Business Directory", "Local Business Search", "Find Businesses", "Business Reviews", "Business Listings"],
	authors: [{ name: "Byron Wade" }, { name: "Byron Wade", url: "https://www.thorbis.com/" }],
	creator: "Byron Wade",
	publisher: "Byron Wade",
	robots: "index, follow",
	alternates: {
		canonical: "https://www.thorbis.com",
		languages: {
			"en-US": "https://www.thorbis.com/en-US",
			"es-ES": "https://www.thorbis.com/es-ES",
		},
	},
	formatDetection: {
		email: false,
		address: false,
		telephone: false,
	},
	category: "directory",
	bookmarks: ["https://www.thorbis.com/"],
	twitter: {
		card: "summary_large_image",
		title: "Thorbis - Discover and Connect with Local Businesses",
		description: "Explore top-rated local businesses with Thorbis. Your comprehensive platform for finding and connecting with businesses in your area.",
		creator: "@thorbis",
		images: {
			url: "https://www.thorbis.com/_next/image?url=%2FThorbisLogo.webp&w=96&q=75",
			alt: "Thorbis Social Logo",
		},
	},
	openGraph: {
		title: "Thorbis - Discover and Connect with Local Businesses",
		description: "Explore top-rated local businesses with Thorbis. Your comprehensive platform for finding and connecting with businesses in your area.",
		url: "https://www.thorbis.com",
		siteName: "Thorbis",
		images: [
			{
				url: "https://www.thorbis.com/api/og?title=Thorbis%20-%20Discover%20and%20Connect%20with%20Local%20Businesses&description=Find%20and%20connect%20with%20top-rated%20local%20businesses",
				width: 800,
				height: 600,
			},
			{
				url: "https://www.thorbis.com/api/og?title=Thorbis%20-%20Discover%20and%20Connect%20with%20Local%20Businesses&description=Find%20and%20connect%20with%20top-rated%20local%20businesses",
				width: 1800,
				height: 1600,
				alt: "Thorbis",
			},
		],
		locale: "en-US",
		type: "website",
	},
};

const jsonLd = {
	"@context": "https://schema.org",
	"@type": "SearchService",
	name: "Thorbis",
	description: "Thorbis provides a powerful platform to discover and connect with top-rated local businesses. Explore and find businesses in your area with ease.",
	url: "https://www.thorbis.com",
	logo: "https://www.thorbis.com/_next/image?url=%2FThorbisLogo.webp&w=96&q=75",
	image: "https://www.thorbis.com/api/og?title=Thorbis%20-%20Discover%20and%20Connect%20with%20Local%20Businesses&description=Find%20and%20connect%20with%20top-rated%20local%20businesses",
	sameAs: ["https://www.facebook.com/thorbis", "https://www.instagram.com/thorbis/?hl=en"],
	potentialAction: {
		"@type": "SearchAction",
		target: "https://www.thorbis.com/search?q={search_term_string}",
		"query-input": "required name=search_term_string",
	},
};

const businesses = [
	{
		id: 1,
		name: "Practically Perfect Day Spa & Salon",
		categories: ["Day Spas", "Massage", "Hair Salons"],
		price: "$$",
		deal: "$50 for $65 Deal",
		description: "She truly has a love for what she does and a talent for skincare and helping to make the world and...",
		logo: "/placeholder.svg",
		isOpenNow: true,
		reviewsCount: 44,
		statusMessage: "Closed until 10:00 AM tomorrow",
		isSponsored: true,
		address: "123 Market St, San Francisco, CA",
		phone: "(123) 456-7890",
		ratings: {
			overall: 4.5,
			totalReviews: 68,
			5: 30,
			4: 25,
			3: 8,
			2: 3,
			1: 2,
		},
		image: "/placeholder.svg",
		images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
		serviceArea: {
			type: "radius",
			value: 10,
		},
		reviews: [
			{
				reviewerName: "John Doe",
				date: "2023-01-01",
				text: "Amazing service, very friendly staff!",
				rating: 5,
			},
			{
				reviewerName: "Jane Smith",
				date: "2023-01-15",
				text: "Had a great experience, highly recommended.",
				rating: 4,
			},
		],
		hours: [
			{ day: "Monday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Tuesday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Wednesday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Thursday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Friday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Saturday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Sunday", open: "Closed", close: "Closed" },
		],
		plusCode: "73G4+M5 San Francisco, California",
	},
	{
		id: 2,
		name: "Urban Retreat Spa",
		categories: ["Spas", "Beauty & Spas"],
		price: "$$",
		deal: "15% off your first visit",
		description: "Relax and rejuvenate with our full range of spa services designed to refresh your mind and body.",
		logo: "/placeholder.svg",
		isOpenNow: true,
		reviewsCount: 27,
		statusMessage: "Open until 8:00 PM",
		isSponsored: false,
		address: "456 Elm St, San Francisco, CA",
		phone: "(234) 567-8901",
		ratings: {
			overall: 4.2,
			totalReviews: 35,
			5: 15,
			4: 12,
			3: 5,
			2: 2,
			1: 1,
		},
		image: "/placeholder.svg",
		images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
		serviceArea: {
			type: "radius",
			value: 8,
		},
		reviews: [
			{
				reviewerName: "Emily Davis",
				date: "2023-02-10",
				text: "Fantastic experience, will definitely come back!",
				rating: 5,
			},
			{
				reviewerName: "Michael Brown",
				date: "2023-02-25",
				text: "Nice place but a bit pricey.",
				rating: 4,
			},
		],
		hours: [
			{ day: "Monday", open: "9:00 AM", close: "8:00 PM" },
			{ day: "Tuesday", open: "9:00 AM", close: "8:00 PM" },
			{ day: "Wednesday", open: "9:00 AM", close: "8:00 PM" },
			{ day: "Thursday", open: "9:00 AM", close: "8:00 PM" },
			{ day: "Friday", open: "9:00 AM", close: "8:00 PM" },
			{ day: "Saturday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Sunday", open: "Closed", close: "Closed" },
		],
		plusCode: "73G5+H6 San Francisco, California",
	},
	{
		id: 3,
		name: "Tranquil Retreat Spa",
		categories: ["Massage", "Day Spas"],
		price: "$$$",
		deal: "Free aromatherapy with every massage",
		description: "Enjoy the ultimate relaxation with our premium massage services and tranquil environment.",
		logo: "/placeholder.svg",
		isOpenNow: false,
		reviewsCount: 19,
		statusMessage: "Closed for renovation",
		isSponsored: true,
		address: "789 Pine St, San Francisco, CA",
		phone: "(345) 678-9012",
		ratings: {
			overall: 4.0,
			totalReviews: 22,
			5: 8,
			4: 9,
			3: 3,
			2: 1,
			1: 1,
		},
		image: "/placeholder.svg",
		images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
		serviceArea: {
			type: "radius",
			value: 12,
		},
		reviews: [
			{
				reviewerName: "Sarah Johnson",
				date: "2023-03-05",
				text: "Wonderful experience, very relaxing.",
				rating: 5,
			},
			{
				reviewerName: "David Wilson",
				date: "2023-03-20",
				text: "Good service but the place could use some updates.",
				rating: 3,
			},
		],
		hours: [
			{ day: "Monday", open: "10:00 AM", close: "7:00 PM" },
			{ day: "Tuesday", open: "10:00 AM", close: "7:00 PM" },
			{ day: "Wednesday", open: "10:00 AM", close: "7:00 PM" },
			{ day: "Thursday", open: "10:00 AM", close: "7:00 PM" },
			{ day: "Friday", open: "10:00 AM", close: "7:00 PM" },
			{ day: "Saturday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Sunday", open: "Closed", close: "Closed" },
		],
		plusCode: "73G6+J7 San Francisco, California",
	},
	{
		id: 4,
		name: "The Zen Den Spa",
		categories: ["Beauty & Spas", "Massage"],
		price: "$",
		deal: "Buy one get one free on select services",
		description: "Escape the hustle and bustle of the city and find your inner peace at our cozy spa.",
		logo: "/placeholder.svg",
		isOpenNow: true,
		reviewsCount: 12,
		statusMessage: "Open until 9:00 PM",
		isSponsored: false,
		address: "101 Maple Ave, San Francisco, CA",
		phone: "(456) 789-0123",
		ratings: {
			overall: 4.3,
			totalReviews: 15,
			5: 6,
			4: 7,
			3: 1,
			2: 1,
			1: 0,
		},
		image: "/placeholder.svg",
		images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
		serviceArea: {
			type: "radius",
			value: 5,
		},
		reviews: [
			{
				reviewerName: "Anna Brown",
				date: "2023-04-01",
				text: "A peaceful retreat, highly recommended!",
				rating: 5,
			},
			{
				reviewerName: "Paul Miller",
				date: "2023-04-12",
				text: "The massage was great but the ambiance could be better.",
				rating: 3,
			},
		],
		hours: [
			{ day: "Monday", open: "10:00 AM", close: "9:00 PM" },
			{ day: "Tuesday", open: "10:00 AM", close: "9:00 PM" },
			{ day: "Wednesday", open: "10:00 AM", close: "9:00 PM" },
			{ day: "Thursday", open: "10:00 AM", close: "9:00 PM" },
			{ day: "Friday", open: "10:00 AM", close: "9:00 PM" },
			{ day: "Saturday", open: "10:00 AM", close: "8:00 PM" },
			{ day: "Sunday", open: "Closed", close: "Closed" },
		],
		plusCode: "73G7+K8 San Francisco, California",
	},
	{
		id: 5,
		name: "Holistic Harmony Spa",
		categories: ["Health & Wellness", "Massage"],
		price: "$$$",
		deal: "20% off for new clients",
		description: "Offering a holistic approach to wellness with a range of therapeutic services tailored to your needs.",
		logo: "/placeholder.svg",
		isOpenNow: true,
		reviewsCount: 35,
		statusMessage: "Open until 7:00 PM",
		isSponsored: true,
		address: "202 Birch Rd, San Francisco, CA",
		phone: "(567) 890-1234",
		ratings: {
			overall: 4.7,
			totalReviews: 40,
			5: 25,
			4: 10,
			3: 4,
			2: 1,
			1: 0,
		},
		image: "/placeholder.svg",
		images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
		serviceArea: {
			type: "radius",
			value: 7,
		},
		reviews: [
			{
				reviewerName: "Laura Williams",
				date: "2023-05-01",
				text: "The best spa experience I've ever had!",
				rating: 5,
			},
			{
				reviewerName: "James Johnson",
				date: "2023-05-15",
				text: "Excellent service but a bit expensive.",
				rating: 4,
			},
		],
		hours: [
			{ day: "Monday", open: "9:00 AM", close: "7:00 PM" },
			{ day: "Tuesday", open: "9:00 AM", close: "7:00 PM" },
			{ day: "Wednesday", open: "9:00 AM", close: "7:00 PM" },
			{ day: "Thursday", open: "9:00 AM", close: "7:00 PM" },
			{ day: "Friday", open: "9:00 AM", close: "7:00 PM" },
			{ day: "Saturday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Sunday", open: "Closed", close: "Closed" },
		],
		plusCode: "73G8+L9 San Francisco, California",
	},
	{
		id: 6,
		name: "Elite Escape Spa",
		categories: ["Massage", "Day Spas"],
		price: "$$$",
		deal: "Free facial with any massage",
		description: "Experience luxury and relaxation at our high-end spa, where every detail is designed for your comfort.",
		logo: "/placeholder.svg",
		isOpenNow: false,
		reviewsCount: 22,
		statusMessage: "Closed until 11:00 AM tomorrow",
		isSponsored: false,
		address: "303 Oak St, San Francisco, CA",
		phone: "(678) 901-2345",
		ratings: {
			overall: 4.6,
			totalReviews: 25,
			5: 12,
			4: 10,
			3: 2,
			2: 1,
			1: 0,
		},
		image: "/placeholder.svg",
		images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
		serviceArea: {
			type: "radius",
			value: 6,
		},
		reviews: [
			{
				reviewerName: "Olivia Lee",
				date: "2023-06-01",
				text: "Fantastic service, worth every penny.",
				rating: 5,
			},
			{
				reviewerName: "Ethan Clark",
				date: "2023-06-15",
				text: "Great place but a little too expensive.",
				rating: 4,
			},
		],
		hours: [
			{ day: "Monday", open: "10:00 AM", close: "7:00 PM" },
			{ day: "Tuesday", open: "10:00 AM", close: "7:00 PM" },
			{ day: "Wednesday", open: "10:00 AM", close: "7:00 PM" },
			{ day: "Thursday", open: "10:00 AM", close: "7:00 PM" },
			{ day: "Friday", open: "10:00 AM", close: "7:00 PM" },
			{ day: "Saturday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Sunday", open: "Closed", close: "Closed" },
		],
		plusCode: "73G9+M1 San Francisco, California",
	},
	{
		id: 7,
		name: "Serenity Spa & Wellness",
		categories: ["Day Spas", "Health & Wellness"],
		price: "$",
		deal: "10% off all services",
		description: "A tranquil sanctuary offering a variety of wellness services to help you relax and rejuvenate.",
		logo: "/placeholder.svg",
		isOpenNow: true,
		reviewsCount: 15,
		statusMessage: "Open until 8:00 PM",
		isSponsored: false,
		address: "404 Pine Ave, San Francisco, CA",
		phone: "(789) 012-3456",
		ratings: {
			overall: 4.4,
			totalReviews: 18,
			5: 7,
			4: 8,
			3: 2,
			2: 1,
			1: 0,
		},
		image: "/placeholder.svg",
		images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
		serviceArea: {
			type: "radius",
			value: 8,
		},
		reviews: [
			{
				reviewerName: "Sophia Martinez",
				date: "2023-07-01",
				text: "Very relaxing atmosphere and great service.",
				rating: 5,
			},
			{
				reviewerName: "Liam Rodriguez",
				date: "2023-07-15",
				text: "Good value for the price.",
				rating: 4,
			},
		],
		hours: [
			{ day: "Monday", open: "10:00 AM", close: "8:00 PM" },
			{ day: "Tuesday", open: "10:00 AM", close: "8:00 PM" },
			{ day: "Wednesday", open: "10:00 AM", close: "8:00 PM" },
			{ day: "Thursday", open: "10:00 AM", close: "8:00 PM" },
			{ day: "Friday", open: "10:00 AM", close: "8:00 PM" },
			{ day: "Saturday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Sunday", open: "Closed", close: "Closed" },
		],
		plusCode: "73G1+N2 San Francisco, California",
	},
	{
		id: 8,
		name: "Relaxation Haven Spa",
		categories: ["Massage", "Spas"],
		price: "$$",
		deal: "20% off your first massage",
		description: "Find your bliss with our selection of massage and relaxation treatments tailored to your needs.",
		logo: "/placeholder.svg",
		isOpenNow: true,
		reviewsCount: 40,
		statusMessage: "Open until 6:00 PM",
		isSponsored: true,
		address: "505 Oak St, San Francisco, CA",
		phone: "(890) 123-4567",
		ratings: {
			overall: 4.8,
			totalReviews: 45,
			5: 30,
			4: 10,
			3: 3,
			2: 2,
			1: 0,
		},
		image: "/placeholder.svg",
		images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
		serviceArea: {
			type: "radius",
			value: 10,
		},
		reviews: [
			{
				reviewerName: "Mia Anderson",
				date: "2023-08-01",
				text: "Absolutely fantastic, highly recommend!",
				rating: 5,
			},
			{
				reviewerName: "William Taylor",
				date: "2023-08-15",
				text: "Great massage but could use more ambiance.",
				rating: 4,
			},
		],
		hours: [
			{ day: "Monday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Tuesday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Wednesday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Thursday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Friday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Saturday", open: "10:00 AM", close: "5:00 PM" },
			{ day: "Sunday", open: "Closed", close: "Closed" },
		],
		plusCode: "73G2+O3 San Francisco, California",
	},
	{
		id: 9,
		name: "The Wellness Retreat Spa",
		categories: ["Health & Wellness", "Beauty & Spas"],
		price: "$$$",
		deal: "Free consultation with any treatment",
		description: "Offering a serene environment and personalized treatments for all your wellness needs.",
		logo: "/placeholder.svg",
		isOpenNow: false,
		reviewsCount: 27,
		statusMessage: "Closed until 9:00 AM tomorrow",
		isSponsored: false,
		address: "606 Maple St, San Francisco, CA",
		phone: "(901) 234-5678",
		ratings: {
			overall: 4.5,
			totalReviews: 30,
			5: 15,
			4: 10,
			3: 3,
			2: 2,
			1: 0,
		},
		image: "/placeholder.svg",
		images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
		serviceArea: {
			type: "radius",
			value: 5,
		},
		reviews: [
			{
				reviewerName: "Charlotte Walker",
				date: "2023-09-01",
				text: "Great place to unwind after a long week.",
				rating: 5,
			},
			{
				reviewerName: "Lucas Hall",
				date: "2023-09-15",
				text: "The consultation was helpful but the treatments are pricey.",
				rating: 4,
			},
		],
		hours: [
			{ day: "Monday", open: "9:00 AM", close: "7:00 PM" },
			{ day: "Tuesday", open: "9:00 AM", close: "7:00 PM" },
			{ day: "Wednesday", open: "9:00 AM", close: "7:00 PM" },
			{ day: "Thursday", open: "9:00 AM", close: "7:00 PM" },
			{ day: "Friday", open: "9:00 AM", close: "7:00 PM" },
			{ day: "Saturday", open: "10:00 AM", close: "6:00 PM" },
			{ day: "Sunday", open: "Closed", close: "Closed" },
		],
		plusCode: "73G3+P4 San Francisco, California",
	},
	{
		id: 10,
		name: "Wade's Plumbing & Septic",
		categories: ["Plumbing", "Septic Services"],
		price: "$$",
		deal: "10% off for first-time customers",
		description: "Reliable plumbing and septic services with over 20 years of experience. We offer comprehensive solutions for all your plumbing needs.",
		logo: "/wades-plumbing-logo.svg",
		isOpenNow: true,
		reviewsCount: 52,
		statusMessage: "Open until 5:00 PM today",
		isSponsored: true,
		address: "123 Main St, Santa Cruz, CA, 95033",
		phone: "(831) 555-1234",
		ratings: {
			overall: 4.8,
			totalReviews: 52,
			5: 35,
			4: 12,
			3: 3,
			2: 2,
			1: 0,
		},
		image: "/wades-plumbing-main-image.jpg",
		images: ["/wades-plumbing-image1.jpg", "/wades-plumbing-image2.jpg", "/wades-plumbing-image3.jpg"],
		serviceArea: {
			type: "radius",
			value: 20,
		},
		reviews: [
			{
				reviewerName: "John Smith",
				date: "2024-06-15",
				text: "Wade's Plumbing & Septic did a fantastic job fixing our leaky pipes. Highly recommended!",
				rating: 5,
			},
			{
				reviewerName: "Jane Doe",
				date: "2024-07-01",
				text: "Very professional and efficient. The septic tank service was top-notch.",
				rating: 4,
			},
		],
		hours: [
			{ day: "Monday", open: "8:00 AM", close: "5:00 PM" },
			{ day: "Tuesday", open: "8:00 AM", close: "5:00 PM" },
			{ day: "Wednesday", open: "8:00 AM", close: "5:00 PM" },
			{ day: "Thursday", open: "8:00 AM", close: "5:00 PM" },
			{ day: "Friday", open: "8:00 AM", close: "5:00 PM" },
			{ day: "Saturday", open: "9:00 AM", close: "3:00 PM" },
			{ day: "Sunday", open: "Closed", close: "Closed" },
		],
		plusCode: "7RVM+PQ Santa Cruz, California",
	},
];

export default function Search() {
	return (
		<>
			<Script data-testid="ldjson" id="json" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd, null, "\t") }} />
			<div>
				<SearchContainer businesses={businesses} />
			</div>
		</>
	);
}
