export const businessCourses = {
	featured: [
		{
			id: "1",
			title: "Complete Digital Marketing Mastery",
			subtitle: "From Zero to Marketing Hero in 8 Weeks",
			description: "Master Facebook Ads, Google Ads, SEO, Content Marketing, and Social Media Strategy. Build campaigns that actually convert.",
			thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop",
			instructor: {
				name: "Sarah Johnson",
				avatar: "https://images.unsplash.com/photo-1494790108755-2616c5e41e9f?w=80&h=80&fit=crop&crop=face",
				title: "Digital Marketing Director",
				company: "Springfield Marketing Agency",
				rating: 4.9,
				students: 2847,
				courses: 12,
			},
			price: 299,
			originalPrice: 499,
			currency: "$",
			discount: 40,
			level: "Beginner to Advanced",
			duration: "12 hours",
			lessons: 48,
			projects: 8,
			certificate: true,
			language: "English",
			category: "Marketing",
			subcategory: "Digital Marketing",
			rating: 4.8,
			reviews: 1247,
			students: 8942,
			lastUpdated: "December 2024",
			bestseller: true,
			featured: true,
			trending: false,
			skills: ["Facebook Ads", "Google Ads", "SEO", "Content Marketing", "Analytics"],
			learningPath: [
				{ title: "Marketing Fundamentals", lessons: 8, completed: 0, locked: false },
				{ title: "Social Media Strategy", lessons: 12, completed: 0, locked: true },
				{ title: "Paid Advertising", lessons: 16, completed: 0, locked: true },
				{ title: "Analytics & Optimization", lessons: 12, completed: 0, locked: true },
			],
			preview: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4",
			whatYouLearn: ["Create profitable Facebook and Instagram ad campaigns", "Master Google Ads and Google Analytics", "Build an SEO strategy that ranks on page 1", "Develop content that converts visitors to customers", "Set up automated email marketing funnels"],
			requirements: ["Basic computer skills", "Access to a computer with internet", "Willingness to learn and practice"],
		},
		{
			id: "2",
			title: "Restaurant Management Excellence",
			subtitle: "Run a Profitable Restaurant Like a Pro",
			description: "Learn inventory management, staff training, customer service, and profit optimization from a 20-year industry veteran.",
			thumbnail: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop",
			instructor: {
				name: "Chef Marcus Rodriguez",
				avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face",
				title: "Restaurant Owner & Consultant",
				company: "Rodriguez Hospitality Group",
				rating: 4.9,
				students: 1523,
				courses: 6,
			},
			price: 199,
			originalPrice: 349,
			currency: "$",
			discount: 43,
			level: "Intermediate",
			duration: "8 hours",
			lessons: 32,
			projects: 5,
			certificate: true,
			language: "English",
			category: "Business",
			subcategory: "Restaurant Management",
			rating: 4.9,
			reviews: 892,
			students: 3456,
			lastUpdated: "November 2024",
			bestseller: false,
			featured: true,
			trending: true,
			skills: ["Inventory Management", "Staff Training", "Cost Control", "Customer Service", "Operations"],
			learningPath: [
				{ title: "Restaurant Basics", lessons: 6, completed: 0, locked: false },
				{ title: "Operations Management", lessons: 10, completed: 0, locked: true },
				{ title: "Financial Control", lessons: 8, completed: 0, locked: true },
				{ title: "Growth Strategies", lessons: 8, completed: 0, locked: true },
			],
			preview: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_2mb.mp4",
			whatYouLearn: ["Optimize inventory and reduce food waste by 30%", "Train staff to deliver exceptional customer service", "Calculate food costs and pricing strategies", "Implement systems for consistent operations", "Scale your restaurant business profitably"],
			requirements: ["Experience in food service (helpful but not required)", "Basic math skills", "Commitment to implementing what you learn"],
		},
		{
			id: "3",
			title: "Home Services Business Blueprint",
			subtitle: "Build a 6-Figure Service Business",
			description: "From plumbing to landscaping - learn how to start, grow, and scale any home services business with proven systems.",
			thumbnail: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&h=400&fit=crop",
			instructor: {
				name: "Mike Thompson",
				avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face",
				title: "Business Coach",
				company: "ServicePro Consulting",
				rating: 4.8,
				students: 4521,
				courses: 15,
			},
			price: 249,
			originalPrice: 399,
			currency: "$",
			discount: 38,
			level: "Beginner",
			duration: "10 hours",
			lessons: 40,
			projects: 6,
			certificate: true,
			language: "English",
			category: "Business",
			subcategory: "Home Services",
			rating: 4.7,
			reviews: 1856,
			students: 6789,
			lastUpdated: "December 2024",
			bestseller: true,
			featured: true,
			trending: false,
			skills: ["Business Planning", "Customer Acquisition", "Pricing Strategy", "Operations", "Scaling"],
			learningPath: [
				{ title: "Business Foundation", lessons: 8, completed: 0, locked: false },
				{ title: "Marketing & Sales", lessons: 12, completed: 0, locked: true },
				{ title: "Operations & Systems", lessons: 10, completed: 0, locked: true },
				{ title: "Growth & Scaling", lessons: 10, completed: 0, locked: true },
			],
			preview: "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_3mb.mp4",
			whatYouLearn: ["Start your home services business from scratch", "Generate leads and convert them to paying customers", "Price your services for maximum profitability", "Build systems that run without you", "Scale to multiple crews and locations"],
			requirements: ["Desire to start or grow a service business", "Basic business understanding", "Willingness to take action"],
		},
	],
	categories: [
		{
			name: "Marketing",
			icon: "📈",
			courses: 24,
			description: "Digital marketing, social media, advertising",
		},
		{
			name: "Business",
			icon: "💼",
			courses: 18,
			description: "Management, operations, strategy",
		},
		{
			name: "Technology",
			icon: "💻",
			courses: 15,
			description: "Web development, software, automation",
		},
		{
			name: "Finance",
			icon: "💰",
			courses: 12,
			description: "Accounting, investing, financial planning",
		},
		{
			name: "Health & Wellness",
			icon: "🏥",
			courses: 9,
			description: "Fitness, nutrition, mental health",
		},
		{
			name: "Real Estate",
			icon: "🏠",
			courses: 8,
			description: "Property management, investing, sales",
		},
	],
	trending: [
		{
			id: "4",
			title: "AI Tools for Small Business",
			price: 149,
			originalPrice: 249,
			rating: 4.6,
			students: 1234,
			instructor: "Dr. Alex Kim",
			thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=400&h=300&fit=crop",
			category: "Technology",
			trending: true,
		},
		{
			id: "5",
			title: "Personal Fitness Coaching Certification",
			price: 199,
			originalPrice: 299,
			rating: 4.8,
			students: 2156,
			instructor: "Jessica Williams",
			thumbnail: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop",
			category: "Health & Wellness",
			trending: true,
		},
	],
};

export const achievements = [
	{ id: 1, name: "First Purchase", icon: "🎯", description: "Complete your first course purchase", unlocked: false },
	{ id: 2, name: "Quick Learner", icon: "⚡", description: "Complete 5 lessons in one day", unlocked: false },
	{ id: 3, name: "Course Completer", icon: "🏆", description: "Finish your first course", unlocked: false },
	{ id: 4, name: "Knowledge Seeker", icon: "📚", description: "Enroll in 3 different courses", unlocked: false },
	{ id: 5, name: "Master Student", icon: "👑", description: "Complete 5 courses", unlocked: false },
];

export const learningStreak = {
	current: 7,
	longest: 15,
	goal: 30,
};
